name: Sedstart Local Linux

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Install Playwright
        run: npm install -g playwright@1.52.0

      - name: Trigger SedStart test run
        uses: sedstart/runlocal@v1
        with:
          api_key: \${{ secrets.SEDSTART_API_KEY_QA }}
          project_id: 270
          test_id: 1186
          profile_id: 330
          browser: chrome
          headless: false
