name: Sedstart Local Windows

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: windows-latest

    steps:
      - name: Install Playwright
        run: npm install -g playwright@1.52.0

      - name: Trigger SedStart test run
        uses: sedstart/runlocal@v1
        with:
          api_key: ${{ secrets.SEDSTART_API_KEY_QA }}
          project_id: 418
          test_id: 1937
          profile_id: 848
          browser: chrome
          headless: false
          environment: QA
